# Generated by Django 5.2.8 on 2026-01-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
    ]
