# Generated by Django 5.2.8 on 2026-01-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_promocode_used_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='used_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
