# Generated by Django 5.2.8 on 2026-01-27 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_promocodeusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodeusage',
            name='promo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.promocode'),
        ),
    ]
