# Generated by Django 5.2.8 on 2025-11-16 17:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('EV', 'Email Verification'), ('2F', 'Two Factor Authentication'), ('PR', 'Password Reset'), ('PU', 'Phone Update')], max_length=2)),
                ('otp_delivery', models.CharField(choices=[('E', 'Email'), ('P', 'Phone')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('H', 'Home Address'), ('O', 'Office Address')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('AE', 'United Arab Emirates'), ('DE', 'Germany'), ('FR', 'France')], max_length=3)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('postal_code', models.CharField(max_length=8)),
                ('recipient_name', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
