# Generated by Django 5.2.8 on 2025-11-17 11:51

import core.validaters
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[core.validaters.validate_indian_phone_number]),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(100000), django.core.validators.MaxLengthValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
