# Generated by Django 5.2.8 on 2025-11-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('AE', 'United Arab Emirates')], max_length=3),
        ),
    ]
