# Generated by Django 5.2.8 on 2025-11-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_google_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
