# Generated by Django 5.2.8 on 2025-11-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_userdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='newsletter_subscribed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='promotional_emails',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sms_notification',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_enabled',
        ),
    ]
