# Generated by Django 5.2.8 on 2026-01-06 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='apartment',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('AE', 'United Arab Emirates')], max_length=8),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
