# Generated by Django 5.2.8 on 2026-01-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_useraddress_apartment_useraddress_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='apartment',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
