# Generated by Django 5.2.8 on 2026-01-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnimage',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='returns.orderreturn'),
        ),
        migrations.AlterField(
            model_name='returnvideo',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='returns.orderreturn'),
        ),
    ]
