# Generated by Django 5.2.8 on 2025-11-18 06:47

import autoslug.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoxType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BoxCategoryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='category_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('box_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.boxcategory')),
            ],
        ),
        migrations.AddField(
            model_name='boxcategory',
            name='box_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.boxtype'),
        ),
        migrations.CreateModel(
            name='HamperBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, help_text='unit is cm', max_digits=5)),
                ('description', models.TextField()),
                ('height', models.DecimalField(decimal_places=2, help_text='unit is cm', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('stock', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('width', models.DecimalField(decimal_places=2, help_text='unit in cm', max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.boxcategory')),
            ],
        ),
    ]
