# Generated by Django 5.2.8 on 2025-12-01 17:18

import autoslug.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamperbox',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='hamperbox',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='hamperbox',
            name='height',
        ),
        migrations.RemoveField(
            model_name='hamperbox',
            name='price',
        ),
        migrations.RemoveField(
            model_name='hamperbox',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='hamperbox',
            name='width',
        ),
        migrations.AlterField(
            model_name='hamperbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BoxImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField()),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('box_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.hamperbox')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=40)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BoxSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height', models.DecimalField(decimal_places=2, help_text='unit is cm', max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, help_text='unit is cm', max_digits=5)),
                ('depth', models.DecimalField(decimal_places=2, help_text='unit is cm', max_digits=5)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('size_label', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('hamper_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalog.hamperbox')),
            ],
            options={
                'unique_together': {('hamper_box', 'size_label')},
            },
        ),
    ]
