# Generated by Django 5.2.8 on 2025-12-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_hamperbox_cost_remove_hamperbox_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxcategory',
            name='box_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.boxtype'),
        ),
    ]
