# Generated by Django 5.2.8 on 2025-12-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_boxcategory_box_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boximage',
            name='image',
            field=models.ImageField(upload_to='box_images/'),
        ),
    ]
