# Generated by Django 5.2.8 on 2025-12-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_decoration_decorationimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='is_inside',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decoration',
            name='is_outside',
            field=models.BooleanField(default=False),
        ),
    ]
