# Generated by Django 5.2.8 on 2025-12-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_decoration_is_inside_decoration_is_outside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
