# Generated by Django 5.2.8 on 2025-12-20 09:40

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_size_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxcategory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='boxcategoryimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='boxsize',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='boxtype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='decoration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='hamperbox',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='hamperbox',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
