# Generated by Django 5.2.8 on 2025-12-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_boxcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoxCategory',
            new_name='BoxMaterial',
        ),
        migrations.RenameModel(
            old_name='BoxCategoryImage',
            new_name='BoxMaterialImage',
        ),
    ]
