# Generated by Django 5.2.8 on 2025-12-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_rename_boxcategory_boxmaterial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamperbox',
            name='description',
            field=models.TextField(),
        ),
    ]
