# Generated by Django 5.2.8 on 2025-12-24 06:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_hamperbox_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoxMaterial',
            new_name='BoxCategory',
        ),
        migrations.RenameModel(
            old_name='BoxMaterialImage',
            new_name='BoxCategoryImage',
        ),
        migrations.AlterField(
            model_name='hamperbox',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
