# Generated by Django 5.2.8 on 2025-12-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_rename_boxmaterial_boxcategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoxType',
            new_name='BoxMaterial',
        ),
    ]
