# Generated by Django 5.2.8 on 2025-12-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_hamperbox_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamperbox',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
