# Generated by Django 5.2.8 on 2026-01-04 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_hamperbox_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorationimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoartion_image', to='catalog.decoration'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_images', to='catalog.productvariant'),
        ),
    ]
