# Generated by Django 5.2.8 on 2026-01-06 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_decorationimages_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boximage',
            name='box_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_images', to='catalog.hamperbox'),
        ),
    ]
