# Generated by Django 5.2.8 on 2026-01-04 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0019_alter_decorationimages_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHamper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.hamperbox')),
                ('box_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.boxsize')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('product_varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='cart.customhamper')),
            ],
        ),
        migrations.CreateModel(
            name='CartDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('outer', 'Outer Decoration'), ('inner', 'Inner Decoration')], max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.decoration')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customhamper')),
            ],
        ),
    ]
