# Generated by Django 5.2.8 on 2026-01-27 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(default=datetime.datetime(2026, 1, 27, 17, 59, 53, 929397, tzinfo=datetime.timezone.utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
