# Generated by Django 5.2.8 on 2026-01-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_shipment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdecoration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order_items/'),
        ),
    ]
