# Generated by Django 5.2.8 on 2026-01-13 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_boxcategory_is_deleted_boxmaterial_is_deleted_and_more'),
        ('order', '0004_orderdecoration_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhamper',
            name='hamper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.boxsize'),
        ),
    ]
