# Generated by Django 5.2.8 on 2026-01-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderhamper_hamper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_date',
            new_name='confirmed_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='expected_delivery',
            new_name='shipped_date',
        ),
    ]
